### ISSUE TITLE
Missing features from the previous version (1.0)

### ISSUE THREAD

**Issue by raghav4** [coding-blocks/hackerblocks.projectx#9]
I've been to the new hacker blocks and I think some of the features from the previous version is missing in this one. Please fix these if possible, I'm listing out those features here. 

1. I can't see any questions more than 10 on a single page. 
2. I can't know the exact category of the problem, the problems are displayed in random order.
3. There's no way I can sort the problems based on the tags like DP graph or whatever just like we could do in the previous version.
4. There's no way I can see the problems that I've already solved.

Thanks

**Comment by farhan787** [comment]
@jatinkatyal13 it would be really helpful if you can look into it.

**Comment by jatinkatyal13** [comment]
Hey @raghav4

Surely we are working towards solving the issues. Here is an update on the problems you mentioned

1. Yes you can't see more than 10 problems on a single page but there is pagination for that which helps in page load time and overall efficiency
2. Feature to filter the problem using tags is now live and working and we are waiting for the designs to display the tags as well.
3. As I stated in the previous point you can now filter the problem using tags
4. Yes you can ! All you have to is select solved problems on the filter on the right hand side

😄 😄

**Comment by raghav4** [comment]
@jatinkatyal13 Site was down maybe, couldn't look then. But now it works perfectly fine! Kudos for the 2.0 version 😄🎉!  Though would love to have suggestions or pre-defined tags to make the search process more hassle-free! 😅
<img width="377" alt="Screenshot 2019-08-22 at 8 45 37 PM" src="https://user-images.githubusercontent.com/20716185/63526957-e2b8dc00-c51d-11e9-9732-b485438e4fb0.png">

**Comment by raghav4** [comment]
Would love to have the tag section like leet code have 
**Leetcode**
<img width="254" alt="Screenshot 2019-08-26 at 12 11 07 AM" src="https://user-images.githubusercontent.com/20716185/63654285-30d81480-c796-11e9-9546-4f8f8964ba5f.png">
**HackerBlocks**
<img width="344" alt="Screenshot 2019-08-26 at 12 11 30 AM" src="https://user-images.githubusercontent.com/20716185/63654287-3b92a980-c796-11e9-9f78-7143e89fa627.png">
It will be helpful to search according to tags, even if one forgets the topics name.

**Comment by jatinkatyal13** [comment]
All the issues mentioned are fixed and live in production!

Thanks for pointing them out @raghav4 😄
